name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Print working directory
      run: |
        pwd
        ls -R
        echo "cd'ing up"
        cd ..
        pwd
        ls -R
    - name: Download Scanners
      run: |
        echo "Downloading the UA"
        curl -LJ "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar" -o "UA.jar"
        echo "Downlaoding the CLI"
        curl "https://downloads.mend.io/cli/linux_amd64/mend" -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
    - name: Print UA Version
      run: |
        echo "Verifying the UA"
        java -jar "UA.jar" -v
        echo "Verifying the CLI version"
        mend version
    - name: Resolve dependencies
      run: |
        pip install .
    - name: Run UA Scan
      run: |
        java -jar UA.jar
      env:
        WS_PYTHON_RUNPOETRYPRESTEP: true
        WS_PROJECTNAME: $GITHUB_REPOSITORY
        WS_PRODUCTNAME: UAScans
        WS_USERKEY: ${{ secrets.WS_USERKEY }}
        WS_APIKEY: ${{ secrets.WS_APIKEY }}
        WS_LOG_LEVEL: "DEBUG"
        WS_SHOWPROGRESSBAR: false
        
    - name: Run Mend CLI
      run: |
        mend dep --update --scope "Aayans Sandbox//UAScans//GH_HiGHS" --non-interactive
      env:
        MEND_USER_KEY: ${{ secrets.WS_USERKEY }}
        MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
        MEND_URL: ${{ secrets.MEND_URL }}
        MEND_LOG_LEVEL: "DEBUG"
